# Generated by Django 4.1.6 on 2023-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_jamoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamoa',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
