# Generated by Django 4.1.6 on 2023-02-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_alter_jamoa_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=90)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
