# Generated by Django 4.1.6 on 2023-02-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_servis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='rasm2',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rasm3',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
