# Generated by Django 4.1.6 on 2023-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email1',
        ),
    ]
