# Generated by Django 4.1.6 on 2023-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_rename_email_email_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='date',
            new_name='date1',
        ),
    ]
